before_install:
  - sudo apt-get install gfortran libblas-dev libblas3gf liblapack-dev liblapack3gf
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
script:
  - nosetests
notifications:
  email: false
